---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "k8s-local-pv.fullname" . }}
  labels:
    k8s-app: {{ template "k8s-local-pv.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: {{ template "k8s-local-pv.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "k8s-local-pv.fullname" . }}-sa
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
{{- if .Values.developerMode }}
          - /bin/bash
          - -c
          - "rm -f /k8s-local-pv ; ln -s /host/root/k8s-local-pv /k8s-local-pv ; rm -f /root/static-pv-provisioner ; ln -s /host/root/static-pv-provisioner /root/static-pv-provisioner ; sleep 120000"
{{ else }}
          - /k8s-local-pv
          - -s
          - -v
{{- range .Values.watcherExtraOptions }}
          - {{ . }}
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /host
            name: host
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      volumes:
      - hostPath:
          path: /
        name: host
