kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "k8s-local-pv.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
#  - apiGroups: [""]
#    resources: ["persistentvolumes/status"]
#    verbs: ["get", "list", "watch", "patch", "update"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "k8s-local-pv.fullname" . }}-binding
  labels:
    k8s-app: {{ template "k8s-local-pv.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-local-pv.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8s-local-pv.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "k8s-local-pv.fullname" . }}-sa
  labels:
    k8s-app: {{ template "k8s-local-pv.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
